### ISSUE TITLE
Вопрос по коду

### ISSUE THREAD

**Issue by waslost0** [AndreiDrang/python-rucaptcha#100]
Код из ReCaptchaV2.py

```python
def captcha_handler(self, site_key: str, page_url: str, **kwargs):
    # Если переданы ещё параметры - вносим их в get_payload ???
    if kwargs:
        for key in kwargs:
            self.get_payload.update({key: kwargs[key]})

    self.post_payload.update({"googlekey": site_key, "pageurl": page_url})
    # получаем ID капчи
    captcha_id = requests.post(self.url_request, data=self.post_payload).json()
```

Для чего дополнительные параметры запроса по типу (cookie, userAgent, proxy) заносить в **get_payload**, если их нам нужно отправить?

**Comment by AndreiDrang** [comment]
Этот параметр был оставлен "на всякий случай", если вдруг АПИ сервиса обновится и будет добавлена куча необязательных параметров, в него не надо передавать параметры типа "cookie, userAgent, proxy".
Данные параметры надо передать в __init__ метода класса ReCaptchaV2.

Недоработка документации\коментариев. Если есть желание - можете дополнить это примерами и дополнительной информацией.
