### ISSUE TITLE
Коды ошибок

### ISSUE THREAD

**Issue by vladiscripts** [AndreiDrang/python-rucaptcha#17]
Можешь добавить, чтобы возвращался не только текст сообщения, но и код ошибки типа int? Вроде `if answer['errorCode'] == 1001:`. 
Проще было бы обрабатывать. Сейчас какая ошибка надо выяснять, парся текстовую  строку ['errorBody'], что довольно необычно.

Имхо, лучше выдавать в `['errorId']`. Но тогда может быть глюк совместимости, у текущих пользователей использующих `['errorId'] == 1`.

**Comment by vladiscripts** [comment]
> Дело в том, что номера есть лишь у некоторых ошибок, тогда либо надо вводить собственную нумерацию для всех ошибок, либо через raise Exception вызывать нужное исключение(но тогда не получится вернуть taskId).
> Думаю стоит обдумать первый вариант.

А что если не вводить свою, а использовать коды сервиса:
```
return { 'errorId': 1, 'errorCode': 'ERROR_KEY_DOES_NOT_EXIST', 'errorBody': ... }
```
Или в модуле errors, если я правильно понимаю, это:
```
return (description, NonExistentKeyError.__doc__)
```

Только description вроде `ERROR: 1004` не симпатичные, их бы либо цифрой либо текстом. Такие и приходят с сервиса?

**Comment by AndreiDrang** [comment]
Код ошибки такой и возвращается, да, error: 1001.
Я думал в принципе для всех ошибок добавить свой уникальны ID, по которому можно было бы идентифицировать ошибку в библиотеке, но оставить и сервисный код ошибки(эти вот надписи капсом и с нижними подчёркиваниями) и полное описание ошибки, вынести это все в json'e под отдельный ключ и все.
