### ISSUE TITLE
Connections issue with 2captcha

### ISSUE THREAD

**Issue by yoyo00x** [AndreiDrang/python-rucaptcha#19]
###Short description of trouble. Краткое описание проблемы.
Hello there is connection problems with the api it produces Remote end closed connection without response error and sometimes it works but once this error starts its like this forever 

###Full description of trouble. Полное описание проблемы.

When i ran the program it sometimes works and sometimes produces this error and when it does its stuck forever i searched online and found this 

https://stackoverflow.com/questions/48105448/python-http-server-client-remote-end-closed-connection-without-response-error

but i dont have expereince in dealing with http/networks so would be helpfull if you fix it

**Comment by AndreiDrang** [comment]
Hi.
Which version of library did u use and which captcha did u solve(i think `ReCaptcha v2`, no?)?

**Comment by yoyo00x** [comment]
yes

**Comment by yoyo00x** [comment]
i can send you my code

**Comment by AndreiDrang** [comment]
No need.
Download version(2.1) from github and try it, we change some things and it can help u.

**Comment by yoyo00x** [comment]
so its fixed?

**Comment by yoyo00x** [comment]
i already installed python version 3.6 and am testing it

**Comment by yoyo00x** [comment]
can you please tell me which version you developed on? so that i have most compatible version

**Comment by AndreiDrang** [comment]
Your error - yep.
But if u use proxy or have troubles with connection u can get other error(like `max_retries`). Because to solve your error we delete `Session()` and can't set `max_retries` param now. We test other solutions but no results now.
> can you please tell me which version you developed on

Just delete your old version, which u download from PyPi, and **clone library from GitHub** repo and install it.

**Comment by yoyo00x** [comment]
you still didn't tell me what the most compatible version

**Comment by AndreiDrang** [comment]
On github, in this repo.

**Comment by yoyo00x** [comment]
![image](https://user-images.githubusercontent.com/17941169/45573035-e1922000-b873-11e8-9915-d027bd879099.png)
the version is not updated yet

**Comment by yoyo00x** [comment]
do i have to do anything extra (change code) or i just install and it wont give me the error?

**Comment by yoyo00x** [comment]
So now "Remote end closed connection without response error" is fixed?

**Comment by yoyo00x** [comment]
Omg i got the issue again!

{'serverAnswer': None, 'captchaSolve': '03AL4dnxrAUx8_FL4mg6-qjfgcnkFzExBX-iC-X0U1-dFYpaDeE75P19dQLiUgWy4qBstGZRkvdI_m3-i4tZkIYkb6XNOFbRMrzrDbisw6eN57vjGpoQWZw8C0A4PMaF7SuWNIH4KdStUlUi9PD65tG_TJVNq6Jr6zXK5De6MkxQT138AGpBCCiB5jwmN8euwkVe3WYV1p14IfHM69U3eRTFjTuZ0cmN2q6oE0RMjs-xI_58MvoKfAS6BTXhVGKmW1GT7Wx1jj0GYdcHBxXXvabGVNnVG37wuupg', 'taskId': '60488434270', 'error': True, 'errorBody': {'text': ConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))}}
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by yoyo00x** [comment]
anticaptcha api is much better
