### ISSUE TITLE
Асинхронные методы для работы с RuCaptchaControl

### ISSUE THREAD

**Issue by Hanyuusha** [AndreiDrang/python-rucaptcha#20]
Будут ли асинхронная имплементация RuCaptchaControl ?

**Comment by AndreiDrang** [comment]
@Hanyuusha Если надо - напишем.
Надо?

**Comment by Hanyuusha** [comment]
Было бы не плохо, у меня есть асинхронный микросервис работающий с этим пакетом, хотелось бы отправлять запросы о не верно разгаданных капчах, что бы не терять деньги.

**Comment by AndreiDrang** [comment]
Окей. 
Подкопилась ещё пара обновлений - буду добавлять.

**Comment by AndreiDrang** [comment]
Так что, следите за обновлениями в репозитории, в ближайшее время.

**Comment by AndreiDrang** [comment]
Можете протестировать добавленный асинхронный метод.

**Comment by Hanyuusha** [comment]
Опубликуйте в PyPi.

**Comment by AndreiDrang** [comment]
Добавили - https://github.com/AndreiDrang/python-rucaptcha/commit/2d4c88548a11077da98da1a6a82afece22338bfb
