### ISSUE TITLE
Pylint alerts corrections as part of an intervention experiment

### ISSUE THREAD

**Issue by evidencebp** [AndreiDrang/python-rucaptcha#306]
**Is your feature request related to a problem? Please describe.**
The feature is not related to a problem but to code readability. 

**Describe the solution you'd like**
I'd like to conduct a software engineering experiment regarding the benefit of [Pylint](https://pypi.org/project/pylint/)  alerts removal.
The experiment is described [here](https://github.com/evidencebp/pylint-intervention/).
In the experiments, Pylint is used with some specific alerts, files are selected for intervention and control.
After the interventions are done, one can wait and examine the results.

I'm asking for your approval for conducting an intervention in your repository.

See examples of interventions in [stanford-oval/storm](https://github.com/stanford-oval/storm/pull/181), [gabfl/vault](https://github.com/gabfl/vault/pull/82), and [coreruleset/coreruleset](https://github.com/coreruleset/coreruleset/pull/3837).

You can see the [planed interventions](https://github.com/evidencebp/pylint-intervention/tree/main/interventions/candidates/AndreiDrang_python-rucaptcha_interventions_October_05_2024.csv)

May I do the interventions, @AndreiDrang ?

**Describe alternatives you've considered**
There is a single broad-exception-caught alert and the rest are too long lines.
This is not critical so an alternative will be to leave it as is.
However, the PR will be easy and there will be beneit in it.

**Additional context**

**Comment by AndreiDrang** [comment]
Hi @evidencebp, lets try it.

**Comment by evidencebp** [comment]
I created a [PR](https://github.com/AndreiDrang/python-rucaptcha/pull/307) withthe changes.

Currently all of them are too long lines so rather minor.
I noted similarity in the file and I guess that some of the files in the control group have similar structure.
@AndreiDrang, can you please not delieretly fix them in the next few months?
That will be a great oppertunity to see empirically the impace of the change on close ojects.

**Comment by evidencebp** [comment]
@AndreiDrang , I would like to consult you regarding the broad-exception-caught alert in src\python_rucaptcha\core\result_handler.py

Too braod exception might lead to problem if the developer planed to catch a specific exception and the exception also catchs and hides different exceptions.

Both get_sync_result (in line 34) and get_async_result (in line 63) catch Exception.
I could not understand which specific exceptions should e handles there.
Can you guide me? Thanks!

**Comment by AndreiDrang** [comment]
Hi
Thanks for your edits and sorry for the long silence.
I will accept your pull request today.
Regarding catching the error you wrote about above - I know this problem, but the code was added because the user doesn't care so much about the type of error if it occurs when receiving the result. Perhaps I'll change this if there are requests from users after the refactoring is finished.
