### ISSUE TITLE
Не использовать диск в ImageCaptcha.py

### ISSUE THREAD

**Issue by shizacat** [AndreiDrang/python-rucaptcha#38]
Смотрю ImageCaptcha.py, в ней вы постоянно используете диск для сохранения файлов (не знаю чем это обусловленно), но не могли бы вы добавить метод работы без него.

Пример подобного кода:
```python
image = io.BytesIO()

try:
    r = requests.get(link, stream=True)
    r.raise_for_status()

    for chunk in r.iter_content(1024):
        image.write(chunk)
except requests.exceptions.RequestException as e:
    print("Что то пошло не так")

image.seek(0)
```

**Comment by AndreiDrang** [comment]
Ну вот, к примеру, если передать параметр `save_format = 'temp'` при инициализации класса `ImageCaptcha` то сохранения на диск не будет. А будет скачан файл капчи с сайта и сразу после `base64.b64encode(...)` будет отправлен на решение.
Сохранение файла на диск довольно удобно использовать при дебаге и специфических задачах вокруг капч.
P.s. Раньше ещё было сохранение как `temporary` файлов но выпилили за ненадобностью.

**Comment by shizacat** [comment]
Ясно,
Спасибо.
