### ISSUE TITLE
need to post the answer?

### ISSUE THREAD

**Issue by pabloapdz** [AndreiDrang/python-rucaptcha#54]
###Short description of trouble. Краткое описание проблемы.
As you know, there are a million completely different sites that request the answer in completely different fields, using this system, will I still need to differentiate all the sites?

###Full description of trouble. Полное описание проблемы.
The question may sometimes be obvious to you, but I don't really get it right, because in the code examples you put in, there is no input from the captcha answer, so I would like to know if it is automatically resolved or if I have to fill it in the input field of the response after acquiring it. Note: I will need to use Captcha, ReCaptcha and Geetest

**Comment by AndreiDrang** [comment]
Hi
> will I still need to differentiate all the sites?

Yep, ofc.
For each captcha u need to use certain captcha module(type).
U need manually check captcha type and choice module.

**Comment by pabloapdz** [comment]
> For each captcha u need to use certain captcha module(type).
> U need manually check captcha type and choice module.

Got it ... Some sites make it virtually impossible to find the callback function by HTML code. Can you tell me if there is any more practical method (other than looking at the HTML code manually through the "inspect" method) of finding the information I need to automatically solve my captcha?

**Comment by AndreiDrang** [comment]
Hm, i think u can write some parser to detect hcaptcha/recaptcha/geetest + params for solving(keys/callbacks for example). But it will be hard to detect image/text/audio captcha(that why it is still not added in library).
