### ISSUE TITLE
reCaptcha V3 API was changed

### ISSUE THREAD

**Issue by mpyrev** [AndreiDrang/python-rucaptcha#55]
reCaptcha V3 API was changed. Now `min_score` value should be between -20 and 20.

python-rucaptcha==2.6.4

**Comment by AndreiDrang** [comment]
But:
https://rucaptcha.com/api-rucaptcha#solving_recaptchav3

**Comment by mpyrev** [comment]
Yeah, sorry about that. They've changed score range only in the answer.
